defmodule RetroHexChatWeb.Icons.Registry do
  @moduledoc """
  Which submodule draws each icon, and which icon a locale or a game resolves to.

  Two consumers read this list and they have to agree, which is why there is one
  list and not two. `RetroHexChatWeb.Icons` generates a component per entry that
  points a `<use>` at the sprite, and `mix retrohex.icons.sprite` renders the art
  behind that same entry into the `<symbol>` the `<use>` resolves to. An icon
  missing here is an icon missing from the sprite.

  Adding an icon: write it in the subject submodule under `components/icons/`,
  then add one line here. The submodules stay the catalog; this is the index.
  """

  @icons [
    # People
    {:icon_community, RetroHexChatWeb.Icons.People},
    {:icon_toolbar_community, RetroHexChatWeb.Icons.People},
    {:icon_connect, RetroHexChatWeb.Icons.People},
    {:icon_robot, RetroHexChatWeb.Icons.People},
    {:icon_dialog_address_book, RetroHexChatWeb.Icons.People},
    {:icon_dialog_nick, RetroHexChatWeb.Icons.People},
    {:icon_tab_contacts, RetroHexChatWeb.Icons.People},
    {:icon_role_owner, RetroHexChatWeb.Icons.People},
    {:icon_role_operator, RetroHexChatWeb.Icons.People},
    {:icon_role_halfop, RetroHexChatWeb.Icons.People},
    {:icon_role_voiced, RetroHexChatWeb.Icons.People},
    {:icon_role_regular, RetroHexChatWeb.Icons.People},
    {:icon_status_user, RetroHexChatWeb.Icons.People},
    {:icon_dialog_profile, RetroHexChatWeb.Icons.People},
    {:icon_btn_profile, RetroHexChatWeb.Icons.People},
    {:icon_dialog_user_modes, RetroHexChatWeb.Icons.People},
    {:icon_btn_user_modes, RetroHexChatWeb.Icons.People},
    {:icon_tab_nicklist, RetroHexChatWeb.Icons.People},

    # Communication
    {:icon_p2p, RetroHexChatWeb.Icons.Communication},
    {:icon_p2p_route, RetroHexChatWeb.Icons.Communication},
    {:icon_protocol_p2p, RetroHexChatWeb.Icons.Communication},
    {:icon_protocol_conference, RetroHexChatWeb.Icons.Communication},
    {:icon_protocol_p2p_compact, RetroHexChatWeb.Icons.Communication},
    {:icon_protocol_conference_compact, RetroHexChatWeb.Icons.Communication},
    {:icon_toolbar_p2p, RetroHexChatWeb.Icons.Communication},
    {:icon_toolbar_conference, RetroHexChatWeb.Icons.Communication},
    {:icon_chat, RetroHexChatWeb.Icons.Communication},
    {:icon_toolbar_chat, RetroHexChatWeb.Icons.Communication},
    {:icon_channels, RetroHexChatWeb.Icons.Communication},
    {:icon_globe, RetroHexChatWeb.Icons.Communication},
    {:icon_websocket, RetroHexChatWeb.Icons.Communication},
    {:icon_webrtc, RetroHexChatWeb.Icons.Communication},
    {:icon_megaphone, RetroHexChatWeb.Icons.Communication},
    {:icon_send, RetroHexChatWeb.Icons.Communication},
    {:icon_link, RetroHexChatWeb.Icons.Communication},
    {:icon_dialog_invite, RetroHexChatWeb.Icons.Communication},
    {:icon_dialog_url, RetroHexChatWeb.Icons.Communication},
    {:icon_dialog_autojoin, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_autojoin, RetroHexChatWeb.Icons.Communication},
    {:icon_tab_channel, RetroHexChatWeb.Icons.Communication},
    {:icon_tab_pm, RetroHexChatWeb.Icons.Communication},
    {:icon_tab_conversations, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_disconnect, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_connect_lightning, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_connect_disabled, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_channel_list, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_toggle_conversations, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_toggle_nicklist, RetroHexChatWeb.Icons.Communication},
    {:icon_toolbar_toggle_conversations, RetroHexChatWeb.Icons.Communication},
    {:icon_toolbar_toggle_nicklist, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_auto_respond, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_url_catcher, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_channel_central, RetroHexChatWeb.Icons.Communication},
    {:icon_toolbar_channel_central, RetroHexChatWeb.Icons.Communication},

    # Media
    {:icon_conference, RetroHexChatWeb.Icons.Media},
    {:icon_microphone, RetroHexChatWeb.Icons.Media},
    {:icon_raise_hand, RetroHexChatWeb.Icons.Media},
    {:icon_camera, RetroHexChatWeb.Icons.Media},
    {:icon_camera_off, RetroHexChatWeb.Icons.Media},
    {:icon_screen_share, RetroHexChatWeb.Icons.Media},
    {:icon_mute, RetroHexChatWeb.Icons.Media},
    {:icon_phone_end, RetroHexChatWeb.Icons.Media},
    {:icon_layout_focus, RetroHexChatWeb.Icons.Media},
    {:icon_layout_side_by_side, RetroHexChatWeb.Icons.Media},
    {:icon_layout_maximize, RetroHexChatWeb.Icons.Media},
    {:icon_pip, RetroHexChatWeb.Icons.Media},
    {:icon_upgrade_video, RetroHexChatWeb.Icons.Media},
    {:icon_devices, RetroHexChatWeb.Icons.Media},
    {:icon_quality_high, RetroHexChatWeb.Icons.Media},
    {:icon_quality_medium, RetroHexChatWeb.Icons.Media},
    {:icon_quality_low, RetroHexChatWeb.Icons.Media},
    {:icon_dialog_sound, RetroHexChatWeb.Icons.Media},
    {:icon_btn_sounds, RetroHexChatWeb.Icons.Media},

    # CallControls: P2P/conference video windows
    {:icon_call_microphone, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_mute, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_camera, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_camera_off, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_screen_share, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_phone_end, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_pip, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_devices, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_layout_auto, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_layout_focus, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_layout_split, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_layout_speaker, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_layout_compact, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_self_view, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_stats, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_mini, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_expand, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_webrtc, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_reactions, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_more, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_raise_hand, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_participants, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_lock, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_close, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_reaction_heart, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_reaction_thumbs_up, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_reaction_clap, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_reaction_laugh, RetroHexChatWeb.Icons.CallControls},
    {:icon_call_reaction_sparkle, RetroHexChatWeb.Icons.CallControls},

    # Files
    {:icon_folder, RetroHexChatWeb.Icons.Files},
    {:icon_app_stack, RetroHexChatWeb.Icons.Files},
    {:icon_notepad, RetroHexChatWeb.Icons.Files},
    {:icon_trash, RetroHexChatWeb.Icons.Files},
    {:icon_backup, RetroHexChatWeb.Icons.Files},
    {:icon_file_send, RetroHexChatWeb.Icons.Files},
    {:icon_choose_file, RetroHexChatWeb.Icons.Files},
    {:icon_dialog_cheatsheet, RetroHexChatWeb.Icons.Files},
    {:icon_dialog_delete, RetroHexChatWeb.Icons.Files},
    {:icon_copy, RetroHexChatWeb.Icons.Files},
    {:icon_dialog_paste, RetroHexChatWeb.Icons.Files},
    {:icon_btn_keyboard, RetroHexChatWeb.Icons.Files},

    # Hardware
    {:icon_laptop, RetroHexChatWeb.Icons.Hardware},
    {:icon_browser, RetroHexChatWeb.Icons.Hardware},
    {:icon_operating_system, RetroHexChatWeb.Icons.Hardware},
    {:icon_server, RetroHexChatWeb.Icons.Hardware},
    {:icon_memory, RetroHexChatWeb.Icons.Hardware},
    {:icon_cpu, RetroHexChatWeb.Icons.Hardware},
    {:icon_plug, RetroHexChatWeb.Icons.Hardware},
    {:icon_table_grid, RetroHexChatWeb.Icons.Hardware},
    {:icon_database, RetroHexChatWeb.Icons.Hardware},
    {:icon_elixir, RetroHexChatWeb.Icons.Hardware},
    {:icon_postgres, RetroHexChatWeb.Icons.Hardware},
    {:icon_tab_display, RetroHexChatWeb.Icons.Hardware},
    {:icon_dialog_channel_list, RetroHexChatWeb.Icons.Hardware},
    {:icon_dialog_channel_central, RetroHexChatWeb.Icons.Hardware},
    {:icon_btn_bell, RetroHexChatWeb.Icons.Hardware},

    # Code
    {:icon_terminal, RetroHexChatWeb.Icons.Code},
    {:icon_git, RetroHexChatWeb.Icons.Code},
    {:icon_code, RetroHexChatWeb.Icons.Code},
    {:icon_dialog_alias, RetroHexChatWeb.Icons.Code},
    {:icon_dialog_auto_respond, RetroHexChatWeb.Icons.Code},
    {:icon_dialog_perform, RetroHexChatWeb.Icons.Code},
    {:icon_tab_commands, RetroHexChatWeb.Icons.Code},
    {:icon_btn_perform, RetroHexChatWeb.Icons.Code},
    {:icon_btn_bot_management, RetroHexChatWeb.Icons.Code},
    {:icon_dialog_bot_management, RetroHexChatWeb.Icons.Code},
    {:icon_dialog_admin_console, RetroHexChatWeb.Icons.Code},

    # Security
    {:icon_lock, RetroHexChatWeb.Icons.Security},
    {:icon_shield, RetroHexChatWeb.Icons.Security},
    {:icon_security, RetroHexChatWeb.Icons.Security},
    {:icon_ban, RetroHexChatWeb.Icons.Security},
    {:icon_globe_blocked, RetroHexChatWeb.Icons.Security},
    {:icon_rules, RetroHexChatWeb.Icons.Security},
    {:icon_dialog_ignore, RetroHexChatWeb.Icons.Security},
    {:icon_tab_modes, RetroHexChatWeb.Icons.Security},
    {:icon_tab_bans, RetroHexChatWeb.Icons.Security},
    {:icon_tab_exceptions, RetroHexChatWeb.Icons.Security},
    {:icon_tab_registration, RetroHexChatWeb.Icons.Security},
    {:icon_privacy, RetroHexChatWeb.Icons.Security},
    {:icon_dialog_ignore_list, RetroHexChatWeb.Icons.Security},
    {:icon_btn_ignore_list, RetroHexChatWeb.Icons.Security},
    {:icon_btn_flood_protection, RetroHexChatWeb.Icons.Security},

    # Arrows
    {:icon_btn_prev, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_next, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_up, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_down, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_refresh, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_export, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_reset, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_join, RetroHexChatWeb.Icons.Arrows},
    {:icon_btn_send, RetroHexChatWeb.Icons.Arrows},
    {:icon_retry, RetroHexChatWeb.Icons.Arrows},
    {:icon_chevron_down, RetroHexChatWeb.Icons.Arrows},
    {:icon_chevron_right, RetroHexChatWeb.Icons.Arrows},
    {:icon_chevron_left, RetroHexChatWeb.Icons.Arrows},
    {:icon_sort_ascending, RetroHexChatWeb.Icons.Arrows},
    {:icon_sort_descending, RetroHexChatWeb.Icons.Arrows},
    {:icon_sort_none, RetroHexChatWeb.Icons.Arrows},
    {:icon_pad_up, RetroHexChatWeb.Icons.Arrows},
    {:icon_pad_down, RetroHexChatWeb.Icons.Arrows},
    {:icon_pad_left, RetroHexChatWeb.Icons.Arrows},
    {:icon_pad_right, RetroHexChatWeb.Icons.Arrows},

    # Marks
    {:icon_list_start, RetroHexChatWeb.Icons.Marks},
    {:icon_list_more, RetroHexChatWeb.Icons.Marks},
    {:icon_btn_add, RetroHexChatWeb.Icons.Marks},
    {:icon_btn_remove, RetroHexChatWeb.Icons.Marks},
    {:icon_btn_ok, RetroHexChatWeb.Icons.Marks},
    {:icon_btn_cancel, RetroHexChatWeb.Icons.Marks},
    {:icon_btn_mark_read, RetroHexChatWeb.Icons.Marks},
    {:icon_accept, RetroHexChatWeb.Icons.Marks},
    {:icon_reject, RetroHexChatWeb.Icons.Marks},
    {:icon_close, RetroHexChatWeb.Icons.Marks},
    {:icon_cancel, RetroHexChatWeb.Icons.Marks},
    {:icon_checkmark, RetroHexChatWeb.Icons.Marks},
    {:icon_warning, RetroHexChatWeb.Icons.Marks},
    {:icon_ellipsis, RetroHexChatWeb.Icons.Marks},
    {:icon_radio_dot, RetroHexChatWeb.Icons.Marks},
    {:icon_check_thin, RetroHexChatWeb.Icons.Marks},
    {:icon_close_pixel, RetroHexChatWeb.Icons.Marks},
    {:icon_close_thin, RetroHexChatWeb.Icons.Marks},
    {:icon_win_minimize, RetroHexChatWeb.Icons.Marks},
    {:icon_win_maximize, RetroHexChatWeb.Icons.Marks},
    {:icon_win_restore, RetroHexChatWeb.Icons.Marks},
    {:icon_fullscreen_enter, RetroHexChatWeb.Icons.Marks},
    {:icon_fullscreen_exit, RetroHexChatWeb.Icons.Marks},
    {:icon_win_help, RetroHexChatWeb.Icons.Marks},
    {:icon_win_cascade, RetroHexChatWeb.Icons.Marks},
    {:icon_win_tile_h, RetroHexChatWeb.Icons.Marks},
    {:icon_win_tile_v, RetroHexChatWeb.Icons.Marks},
    {:icon_win_minimize_all, RetroHexChatWeb.Icons.Marks},

    # Tools
    {:icon_wrench, RetroHexChatWeb.Icons.Tools},
    {:icon_palette, RetroHexChatWeb.Icons.Tools},
    {:icon_dialog_nick_colors, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_nick_colors, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_edit, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_save, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_apply, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_search, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_set_topic, RetroHexChatWeb.Icons.Tools},
    {:icon_dialog_options, RetroHexChatWeb.Icons.Tools},
    {:icon_dialog_custom_menus, RetroHexChatWeb.Icons.Tools},
    {:icon_tab_control, RetroHexChatWeb.Icons.Tools},
    {:icon_tab_colors, RetroHexChatWeb.Icons.Tools},
    {:icon_group_view, RetroHexChatWeb.Icons.Tools},
    {:icon_group_tools, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_find, RetroHexChatWeb.Icons.Tools},
    {:icon_toolbar_find, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_settings, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_address_book, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_alias_editor, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_custom_menus, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_timers, RetroHexChatWeb.Icons.Tools},
    {:icon_btn_highlight_words, RetroHexChatWeb.Icons.Tools},

    # Alerts
    {:icon_document_alert, RetroHexChatWeb.Icons.Alerts},
    {:icon_question, RetroHexChatWeb.Icons.Alerts},
    {:icon_dialog_about, RetroHexChatWeb.Icons.Alerts},
    {:icon_dialog_notifications, RetroHexChatWeb.Icons.Alerts},
    {:icon_dialog_highlight, RetroHexChatWeb.Icons.Alerts},
    {:icon_dialog_flood, RetroHexChatWeb.Icons.Alerts},
    {:icon_tab_general, RetroHexChatWeb.Icons.Alerts},
    {:icon_tab_notify, RetroHexChatWeb.Icons.Alerts},
    {:icon_tab_notifications, RetroHexChatWeb.Icons.Alerts},
    {:icon_tab_status, RetroHexChatWeb.Icons.Alerts},
    {:icon_group_notifications, RetroHexChatWeb.Icons.Alerts},
    {:icon_group_help, RetroHexChatWeb.Icons.Alerts},
    {:icon_lightbulb, RetroHexChatWeb.Icons.Alerts},
    {:icon_btn_dnd, RetroHexChatWeb.Icons.Alerts},
    {:icon_dialog_away, RetroHexChatWeb.Icons.Alerts},
    {:icon_btn_away, RetroHexChatWeb.Icons.Alerts},
    {:icon_btn_dnd_active, RetroHexChatWeb.Icons.Alerts},
    {:icon_btn_help_topics, RetroHexChatWeb.Icons.Alerts},

    # Symbols
    {:icon_dollar, RetroHexChatWeb.Icons.Symbols},
    {:icon_chart_bars, RetroHexChatWeb.Icons.Symbols},
    {:icon_star, RetroHexChatWeb.Icons.Symbols},
    {:icon_bug, RetroHexChatWeb.Icons.Symbols},
    {:icon_heart, RetroHexChatWeb.Icons.Symbols},
    {:icon_thumbs_up, RetroHexChatWeb.Icons.Symbols},
    {:icon_clap, RetroHexChatWeb.Icons.Symbols},
    {:icon_laugh, RetroHexChatWeb.Icons.Symbols},
    {:icon_sparkle, RetroHexChatWeb.Icons.Symbols},
    {:icon_pin, RetroHexChatWeb.Icons.Symbols},
    {:icon_legal, RetroHexChatWeb.Icons.Symbols},
    {:icon_clock, RetroHexChatWeb.Icons.Symbols},
    {:icon_btn_ignore, RetroHexChatWeb.Icons.Symbols},
    {:icon_status_signal, RetroHexChatWeb.Icons.Symbols},
    {:icon_dialog_kick, RetroHexChatWeb.Icons.Symbols},
    {:icon_dice, RetroHexChatWeb.Icons.Symbols},
    {:icon_joystick, RetroHexChatWeb.Icons.Symbols},
    {:icon_rss, RetroHexChatWeb.Icons.Symbols},
    {:icon_tag, RetroHexChatWeb.Icons.Symbols},
    {:icon_hex_stone, RetroHexChatWeb.Icons.Symbols},

    # Formatting
    {:icon_fmt_toolbar, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_bold, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_italic, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_underline, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_color, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_reverse, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_reset, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_strip, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_emoji, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_mode_irc, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_mode_markdown, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_mode_plain, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_preview, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_heading, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_strike, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_inline_code, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_code_block, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_quote, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_bulleted_list, RetroHexChatWeb.Icons.Formatting},
    {:icon_fmt_ordered_list, RetroHexChatWeb.Icons.Formatting},

    # Games
    {:icon_game_pong, RetroHexChatWeb.Icons.Games},
    {:icon_game_trails, RetroHexChatWeb.Icons.Games},
    {:icon_game_tanks, RetroHexChatWeb.Icons.Games},
    {:icon_game_space, RetroHexChatWeb.Icons.Games},
    {:icon_game_gravity, RetroHexChatWeb.Icons.Games},
    {:icon_game_debris, RetroHexChatWeb.Icons.Games},
    {:icon_game_breakout, RetroHexChatWeb.Icons.Games},
    {:icon_game_warlords, RetroHexChatWeb.Icons.Games},
    {:icon_game_raid, RetroHexChatWeb.Icons.Games},
    {:icon_game_boxing, RetroHexChatWeb.Icons.Games},
    {:icon_game_outlaw, RetroHexChatWeb.Icons.Games},
    {:icon_game_invaders, RetroHexChatWeb.Icons.Games},
    {:icon_game_enduro, RetroHexChatWeb.Icons.Games},
    {:icon_game_tennis, RetroHexChatWeb.Icons.Games},
    {:icon_game_skiing, RetroHexChatWeb.Icons.Games},
    {:icon_game_frost, RetroHexChatWeb.Icons.Games},
    {:icon_game_hockey, RetroHexChatWeb.Icons.Games},
    {:icon_game_doom, RetroHexChatWeb.Icons.Games},
    {:icon_game_freedoom1, RetroHexChatWeb.Icons.Games},
    {:icon_game_freedoom2, RetroHexChatWeb.Icons.Games},
    {:icon_game_freedm, RetroHexChatWeb.Icons.Games},
    {:icon_game_chex, RetroHexChatWeb.Icons.Games},
    {:icon_game_hacx, RetroHexChatWeb.Icons.Games},
    {:icon_game_rekkr, RetroHexChatWeb.Icons.Games},
    {:icon_game_quake, RetroHexChatWeb.Icons.Games},
    {:icon_game_quake2, RetroHexChatWeb.Icons.Games},
    {:icon_game_librequake, RetroHexChatWeb.Icons.Games},
    {:icon_game_wolfenstein, RetroHexChatWeb.Icons.Games},
    {:icon_game_halflife, RetroHexChatWeb.Icons.Games},
    {:icon_game_bass, RetroHexChatWeb.Icons.Games},
    {:icon_game_drascula, RetroHexChatWeb.Icons.Games},
    {:icon_game_dreamweb, RetroHexChatWeb.Icons.Games},
    {:icon_game_fotaq, RetroHexChatWeb.Icons.Games},
    {:icon_game_lure, RetroHexChatWeb.Icons.Games},
    {:icon_game_soltys, RetroHexChatWeb.Icons.Games},
    {:icon_game_arcade, RetroHexChatWeb.Icons.Games},
    {:icon_game_generic, RetroHexChatWeb.Icons.Games},

    # Flags
    {:icon_flag_en, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_pt_br, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_pt_pt, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_es, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_fr, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_de, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_ja, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_zh_hans, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_zh_hant, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_id, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_ru, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_it, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_pl, RetroHexChatWeb.Icons.Flags},
    {:icon_flag_nl, RetroHexChatWeb.Icons.Flags},

    # New button icons (showcase design system)
    {:icon_btn_open, RetroHexChatWeb.Icons.Files},
    {:icon_btn_page, RetroHexChatWeb.Icons.Files},
    {:icon_btn_trash, RetroHexChatWeb.Icons.Files},
    {:icon_btn_star, RetroHexChatWeb.Icons.Symbols},
    {:icon_sword, RetroHexChatWeb.Icons.Symbols},
    {:icon_btn_play, RetroHexChatWeb.Icons.Media},
    {:icon_btn_info, RetroHexChatWeb.Icons.Alerts},
    {:icon_btn_link, RetroHexChatWeb.Icons.Communication},
    {:icon_btn_menu, RetroHexChatWeb.Icons.Tools}
  ]

  # Two icons are picked at render time rather than named at the call site: the
  # locale menu asks for a flag and a game card asks for its box art. Both still
  # resolve to an ordinary icon above, so they cost the sprite nothing extra.
  @flags %{
    "en" => :icon_flag_en,
    "pt_BR" => :icon_flag_pt_br,
    "pt_PT" => :icon_flag_pt_pt,
    "es" => :icon_flag_es,
    "fr" => :icon_flag_fr,
    "de" => :icon_flag_de,
    "ja" => :icon_flag_ja,
    "zh_hans" => :icon_flag_zh_hans,
    "zh_hant" => :icon_flag_zh_hant,
    "id" => :icon_flag_id,
    "ru" => :icon_flag_ru,
    "it" => :icon_flag_it,
    "pl" => :icon_flag_pl,
    "nl" => :icon_flag_nl
  }

  @games %{
    "hex_pong" => :icon_game_pong,
    "light_trails" => :icon_game_trails,
    "pixel_tanks" => :icon_game_tanks,
    "star_duel" => :icon_game_space,
    "gravity_well" => :icon_game_gravity,
    "debris_field" => :icon_game_debris,
    "block_breakers" => :icon_game_breakout,
    "hex_warlords" => :icon_game_warlords,
    "hex_raid" => :icon_game_raid,
    "hex_raid_pacifist" => :icon_game_raid,
    "hex_raid_blitz" => :icon_game_raid,
    "hex_boxing" => :icon_game_boxing,
    "hex_outlaw" => :icon_game_outlaw,
    "hex_outlaw_ricochet" => :icon_game_outlaw,
    "hex_outlaw_stagecoach" => :icon_game_outlaw,
    "hex_outlaw_nml" => :icon_game_outlaw,
    "hex_invaders" => :icon_game_invaders,
    "hex_invaders_coop" => :icon_game_invaders,
    "hex_invaders_blitz" => :icon_game_invaders,
    "hex_enduro" => :icon_game_enduro,
    "hex_enduro_night" => :icon_game_enduro,
    "hex_enduro_sprint" => :icon_game_enduro,
    "hex_tennis" => :icon_game_tennis,
    "hex_tennis_quick" => :icon_game_tennis,
    "hex_tennis_sudden" => :icon_game_tennis,
    "hex_skiing" => :icon_game_skiing,
    "hex_skiing_escape" => :icon_game_skiing,
    "hex_skiing_clean" => :icon_game_skiing,
    "hex_frost" => :icon_game_frost,
    "hex_frost_blizzard" => :icon_game_frost,
    "hex_frost_peaceful" => :icon_game_frost,
    "hex_hockey" => :icon_game_hockey,
    "hex_hockey_blitz" => :icon_game_hockey,
    "hex_hockey_showdown" => :icon_game_hockey,
    "doom_shareware" => :icon_game_doom,
    "freedoom1" => :icon_game_freedoom1,
    "freedoom2" => :icon_game_freedoom2,
    "freedm" => :icon_game_freedm,
    "chex_quest" => :icon_game_chex,
    "hacx" => :icon_game_hacx,
    "rekkr" => :icon_game_rekkr,
    "quake_shareware" => :icon_game_quake,
    "librequake" => :icon_game_librequake,
    "quake2_shareware" => :icon_game_quake2,
    "wolfenstein_3d" => :icon_game_wolfenstein,
    "halflife_uplink" => :icon_game_halflife,
    "scummvm_bass" => :icon_game_bass,
    "scummvm_drascula" => :icon_game_drascula,
    "scummvm_dreamweb" => :icon_game_dreamweb,
    "scummvm_fotaq" => :icon_game_fotaq,
    "scummvm_lure" => :icon_game_lure,
    "scummvm_soltys" => :icon_game_soltys
  }

  @flag_fallback :icon_globe
  @game_fallback :icon_game_generic

  @doc """
  Every icon, as `{component_name, drawing_module}`, in catalog order.
  """
  @spec all() :: [{atom(), module()}]
  def all, do: @icons

  @doc """
  The `<symbol>` id an icon occupies inside the sprite document.
  """
  @spec sprite_id(atom()) :: String.t()
  def sprite_id(name) when is_atom(name), do: Atom.to_string(name)

  @doc """
  The flag icon for a locale code, falling back to a globe for anything unlisted.
  """
  @spec flag(String.t()) :: atom()
  def flag(locale), do: Map.get(@flags, locale, @flag_fallback)

  @doc """
  The box art for a game id, falling back to a generic cartridge.
  """
  @spec game(String.t()) :: atom()
  def game(game_id), do: Map.get(@games, game_id, @game_fallback)
end
