import {
  Browser,
  BrowserContext,
  Locator,
  Page,
  expect,
  test,
} from "@playwright/test";
import { ConnectPage } from "../pages/ConnectPage";
import { ChatPage } from "../pages/ChatPage";
import { shot } from "../helpers/screenshots";

/**
 * The runtime inspection windows, driven through the real desktop.
 *
 * These read the node the server is running on, so the assertions target facts
 * true of any BEAM running this application — the emulator banner, a process
 * that is always registered, this application being loaded — never fixed
 * numbers that would differ between a laptop and the production box.
 *
 * Carries `shot()` evidence points at each window, so the visual state of the
 * whole set can be regenerated by anyone with:
 *
 *     make e2e.shots FILE=tests/chat-system-windows.spec.ts
 */

const ADMIN_NICK = "TestAdmin";
const ADMIN_PW = "adminpass1";

type TestUser = {
  chat: ChatPage;
  ctx: BrowserContext;
  page: Page;
};

async function expectNoHorizontalOverflow(locator: Page | Locator) {
  const overflow = await locator.locator("[data-testid]").evaluateAll((nodes) =>
    nodes
      .map((node) => {
        const element = node as HTMLElement;
        return {
          testid: element.dataset.testid || element.id || element.tagName,
          clientWidth: element.clientWidth,
          scrollWidth: element.scrollWidth,
        };
      })
      .filter((entry) => entry.scrollWidth > entry.clientWidth + 2),
  );

  expect(overflow).toEqual([]);
}

async function signedInAdmin(browser: Browser): Promise<TestUser> {
  const ctx = await browser.newContext();
  const page = await ctx.newPage();
  const connect = new ConnectPage(page);
  const chat = new ChatPage(page);

  await connect.open();
  await connect.signIn(ADMIN_NICK, ADMIN_PW);
  await chat.waitUntilConnected();

  return { chat, ctx, page };
}

test.describe("System windows", () => {
  test("the overview reports the node's identity, limits and memory split", async ({
    browser,
  }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_home");

      // The banner is the emulator describing itself; if this is wrong, every
      // other reading in the window is suspect.
      await expect(window).toContainText("Erlang/OTP");
      await expect(window).toContainText("System limits");
      await expect(window).toContainText("Run queues");
      await expect(window).toContainText("Total usage:");

      await shot(window, "overview");

      // The memory bar is only honest if its segments sum to the total, which
      // is what makes it readable as proportions at all.
      const segments = window.locator(
        '[data-testid="system-home-memory"] [title]',
      );
      expect(await segments.count()).toBe(6);

      await window.getByTestId("system-home-refresh").click();
      await expect(window).toContainText("System limits");
      await shot(window, "overview-after-refresh");
    } finally {
      await admin.ctx.close();
    }
  });

  test("the process listing filters and reorders on the live node", async ({
    browser,
  }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_processes");

      await expect(window).toContainText("code_server");
      await shot(window, "processes-unfiltered");

      await window.getByLabel("Filter").fill("gen_server");
      await expect(window).toContainText("gen_server");
      await shot(window, "processes-filtered");

      // Sorting by mailbox depth is the reason this window exists: a process
      // whose queue outgrows its drain rate is the one worth finding.
      await window.locator('[phx-value-column="message_queue_len"]').click();
      await expect(
        window.locator('[phx-value-column="message_queue_len"]'),
      ).toHaveAttribute("data-active", "true");
      await shot(window, "processes-sorted-by-mailbox");
    } finally {
      await admin.ctx.close();
    }
  });

  test("every runtime listing opens and renders rows", async ({ browser }) => {
    const admin = await signedInAdmin(browser);

    try {
      for (const source of ["ports", "sockets", "ets", "applications"]) {
        const window = await admin.chat.openSystemWindow(
          `open_system_${source}`,
        );

        await expect(window.locator("table")).toBeVisible();
        await shot(window, source);
      }

      // Applications is the one listing whose contents are predictable: the
      // node is by definition running this application.
      const applications = admin.page.getByTestId("system-applications-window");
      await applications.getByLabel("Filter").fill("retro_hex_chat");
      await expect(applications).toContainText("retro_hex_chat");
      await shot(applications, "applications-filtered");
    } finally {
      await admin.ctx.close();
    }
  });

  test("the host readings render, or say they cannot be read", async ({
    browser,
  }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_os");

      // Every :os_mon gauge is platform-dependent, so the contract is not that
      // a number appears — it is that the window resolves either way.
      await expect(window).toContainText("Host");
      await expect(window).toContainText("Processors");
      await shot(window, "os-data");
    } finally {
      await admin.ctx.close();
    }
  });

  test("app info counts the channels and people actually present", async ({
    browser,
  }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_app_info");

      await expect(window).toContainText("Channels");
      await expect(window).toContainText("People");
      // The admin is signed in and in #lobby, so occupancy is never zero here.
      await expect(window).toContainText("lobby");
      await shot(window, "app-info");
    } finally {
      await admin.ctx.close();
    }
  });

  test("a database report runs and returns rows", async ({ browser }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_database");

      await shot(window, "database-empty");

      // cache_hit is the one report guaranteed to work on any Postgres with
      // no extensions installed and no rows of its own required.
      await window.getByLabel("Report").selectOption("cache_hit");
      await expect(window.locator("table")).toBeVisible();
      await shot(window, "database-cache-hit");

      // One window, unrelated listings in turn. Widths measured for the first
      // report describe columns the second does not have: keeping them pinned
      // the table to the sum of the surviving keys and left every new column
      // with no width at all — rows present in the DOM and invisible on screen.
      const table = window.getByTestId("system-database-table");
      const first = table.locator(".retro-table__head").first();
      const box = (await first.boundingBox())!;
      await admin.page.mouse.move(box.x + box.width, box.y + box.height / 2);
      await admin.page.mouse.down();
      await admin.page.mouse.move(
        box.x + box.width + 80,
        box.y + box.height / 2,
        {
          steps: 6,
        },
      );
      await admin.page.mouse.up();

      await window.getByLabel("Report").selectOption("table_size");
      await expect(
        table.locator('.retro-table__head[data-column="schema"]'),
      ).toBeVisible();

      for (const column of ["schema", "name", "size"]) {
        const width = (await table
          .locator(`.retro-table__head[data-column="${column}"]`)
          .boundingBox())!.width;
        expect(width, `${column} column has a readable width`).toBeGreaterThan(
          20,
        );
      }
      await shot(window, "database-report-switched");
    } finally {
      await admin.ctx.close();
    }
  });

  test("metrics charts subscribe to a group and draw", async ({ browser }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_metrics");

      await expect(window).toContainText("Live metrics");

      // Domain is this product's own instrumentation, so it is the group worth
      // proving reachable.
      await window.getByTestId("system-metrics-group-Domain").click();
      await expect(
        window.getByTestId("system-metrics-group-Domain"),
      ).toHaveAttribute("aria-pressed", "true");
      await shot(window, "metrics-domain-group");

      // An empty chart proves only that the window rendered. Driving the
      // server into emitting the events a group is subscribed to, then waiting
      // past a refresh tick, is what proves the whole path — handler,
      // collector, push, canvas.
      await window.getByTestId("system-metrics-group-LiveView").click();
      for (const message of ["metrics probe one", "metrics probe two"]) {
        await admin.chat.sendMessage(message);
      }
      await admin.page.waitForTimeout(2500);
      await shot(window, "metrics-liveview-with-data");
    } finally {
      await admin.ctx.close();
    }
  });

  test("the live log streams only once asked", async ({ browser }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow(
        "open_system_request_logger",
      );

      // Nothing is installed until the operator presses Stream — the whole
      // point of the toggle.
      await expect(window).toContainText("Press Stream to tail the server log");
      await shot(window, "live-log-idle");

      await window.getByTestId("system-log-toggle").click();
      await expect(window).toContainText("Stop");
      await shot(window, "live-log-streaming");

      // The e2e node runs at LOG_LEVEL=warning, so nothing at info can ever
      // reach a handler — the primary logger drops it first. The window has to
      // say so rather than sit silent and look broken. Asserting the notice is
      // what proves it knows the difference between "quiet" and "impossible".
      await expect(window.getByTestId("system-log-unreachable")).toBeVisible();
      await shot(window, "live-log-unreachable-level");

      // Raising the selection to what the node actually emits clears it.
      await window.getByLabel("Level").selectOption("warning");
      await expect(window.getByTestId("system-log-unreachable")).toHaveCount(0);
    } finally {
      await admin.ctx.close();
    }
  });

  test("the Oban health window groups contracts into tabs without horizontal overflow", async ({
    browser,
  }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_oban");

      await expect(window).toContainText("Oban health");
      await expect(
        window.getByTestId("system-oban-tab-overview"),
      ).toHaveAttribute("aria-selected", "true");
      await expectNoHorizontalOverflow(window);
      await shot(window, "oban-overview");

      for (const [tab, expectedText] of [
        ["queues", "Recent jobs"],
        ["bots", "Bot event log jobs"],
        ["maintenance", "Ignore expired cleanup"],
        ["previews", "Final failures"],
        ["persistence", "Preference persistence"],
      ] as const) {
        await window.getByTestId(`system-oban-tab-${tab}`).click();
        await expect(
          window.getByTestId(`system-oban-tab-${tab}`),
        ).toHaveAttribute("aria-selected", "true");
        await expect(
          window.locator("#system-oban-dialog-tabs"),
        ).toHaveAttribute("data-active-tab", tab);
        await expect(
          window.getByTestId(`system-oban-tabpanel-${tab}`),
        ).toBeVisible();
        await expect(window).toContainText(expectedText);
        await expectNoHorizontalOverflow(window);
        await shot(window, `oban-${tab}`);
      }
    } finally {
      await admin.ctx.close();
    }
  });

  test("the listing is resized, narrowed and read row by row", async ({
    browser,
  }) => {
    const admin = await signedInAdmin(browser);

    try {
      const window = await admin.chat.openSystemWindow("open_system_ets");
      const table = window.getByTestId("system-ets-table");
      const name = table.locator('.retro-table__head[data-column="name"]');

      // Widths are pinned from the first paint. Until this attribute is on the
      // root, nothing below is being driven by the hook at all.
      await expect(table).toHaveAttribute("data-layout", "fixed");
      await shot(window, "listing-as-opened");

      // Dragging a heading's right edge moves that column and only that one.
      const before = await name.boundingBox();
      const others = await table
        .locator('.retro-table__head[data-column="size"]')
        .boundingBox();
      await admin.page.mouse.move(
        before!.x + before!.width,
        before!.y + before!.height / 2,
      );
      await admin.page.mouse.down();
      await admin.page.mouse.move(
        before!.x + before!.width + 90,
        before!.y + before!.height / 2,
        { steps: 8 },
      );
      await admin.page.mouse.up();

      const widened = await name.boundingBox();
      expect(widened!.width).toBeGreaterThan(before!.width + 60);
      expect(
        (await table
          .locator('.retro-table__head[data-column="size"]')
          .boundingBox())!.width,
      ).toBeCloseTo(others!.width, 0);
      await shot(window, "listing-column-widened");

      // The drag must not also have sorted: the heading it ended on is a
      // button, and a click leaking through would reorder the whole listing.
      await expect(name).toHaveAttribute("aria-sort", "none");

      // Double-clicking the same edge fits the column to its longest value.
      await admin.page.mouse.dblclick(
        widened!.x + widened!.width,
        widened!.y + widened!.height / 2,
      );
      await expect
        .poll(async () => (await name.boundingBox())!.width)
        .not.toBe(widened!.width);

      // Right-clicking the header offers the columns; switching one off closes
      // the gap it was holding rather than leaving an empty band.
      await table
        .locator("[data-retro-table-head-row]")
        .click({ button: "right" });
      const menu = window.getByTestId("context-menu-system-ets-table-columns");
      await expect(menu).toBeVisible();
      await shot(window, "listing-column-menu");

      await window.getByTestId("system-ets-table-column-owner").click();
      await expect(
        table.locator('.retro-table__head[data-column="owner"]'),
      ).toBeHidden();
      await expect(
        table.locator('.retro-table__cell[data-column="owner"]').first(),
      ).toBeHidden();
      await shot(window, "listing-column-hidden");

      // And the reset brings every one of them back.
      await table
        .locator("[data-retro-table-head-row]")
        .click({ button: "right" });
      await window.getByTestId("system-ets-table-columns-reset").click();
      await expect(
        table.locator('.retro-table__head[data-column="owner"]'),
      ).toBeVisible();

      // A row answers the pointer and then the keyboard, which is what makes a
      // long listing readable without reaching back for the mouse.
      const rows = table.locator(".retro-table__row");
      await rows.nth(1).click();
      await expect(rows.nth(1)).toHaveAttribute("aria-selected", "true");

      await admin.page.keyboard.press("ArrowDown");
      await expect(rows.nth(2)).toHaveAttribute("aria-selected", "true");
      await expect(rows.nth(1)).toHaveAttribute("aria-selected", "false");

      await admin.page.keyboard.press("Home");
      await expect(rows.first()).toHaveAttribute("aria-selected", "true");
      await shot(window, "listing-row-selected");
    } finally {
      await admin.ctx.close();
    }
  });

  test("open windows are reachable from the taskbar", async ({ browser }) => {
    const admin = await signedInAdmin(browser);

    try {
      // The defect this guards: these windows rendered, focused and cascaded
      // correctly while having no taskbar button at all, so minimising one put
      // it out of reach entirely.
      await admin.chat.openSystemWindow("open_system_processes");
      await expect(
        admin.page.locator('[data-window-taskbar="system-processes"]'),
      ).toBeVisible();

      // A second window of the same family collapses both into one group
      // button rather than adding a twelfth entry to the strip.
      await admin.chat.openSystemWindow("open_system_ets");
      await expect(
        admin.page.getByTestId("taskbar-group-system"),
      ).toBeVisible();
      await shot(admin.page, "taskbar-system-group");
    } finally {
      await admin.ctx.close();
    }
  });

  test("the windows coexist on one desktop", async ({ browser }) => {
    const admin = await signedInAdmin(browser);

    try {
      await admin.chat.openSystemWindow("open_system_home");
      await admin.chat.openSystemWindow("open_system_processes");
      await admin.chat.openSystemWindow("open_system_ets");

      await expect(admin.page.getByTestId("system-home-window")).toBeVisible();
      await expect(
        admin.page.getByTestId("system-processes-window"),
      ).toBeVisible();
      await expect(admin.page.getByTestId("system-ets-window")).toBeVisible();

      await shot(admin.page, "desktop-with-three-windows");
    } finally {
      await admin.ctx.close();
    }
  });
});
