"""Migrate the tiles named in manifest.json into semantic JS sprite modules.

Reads `manifest.json` (semantic_name -> {sheet, col, row}), mirrors each sliced
PNG into `assets/js/lib/space/sprites/tiles/<name>.js`, regenerates the
`sprites/index.js` registry, and writes a labeled verification montage so the
name->art mapping can be eyeballed.

Run `slice.py` first. Usage:
    python3 migrate.py
"""

import json
import os

from PIL import Image

from png2js import convert, convert_image

TOOLS = os.path.dirname(os.path.abspath(__file__))
GFX = os.path.dirname(TOOLS)
REPO = os.path.abspath(os.path.join(GFX, "..", "..", "..", ".."))
SLICED = os.path.join(GFX, "sliced")
SRC = os.path.join(REPO, "apps", "retro_hex_chat_web", "assets", "js", "lib", "space", "sprites")


def sliced_png(sheet, col, row):
    return os.path.join(SLICED, sheet, f"c{col:02d}_r{row:02d}.png")


# A tile spec may span several tiles (w/h in tiles): those are cropped straight
# from the source sheet so multi-tile props (houses, big trees) become one
# sprite module.
def _extract(name, spec, tile=16):
    dst = os.path.join(SRC, "tiles", f"{name}.js")
    w, h = spec.get("w", 1), spec.get("h", 1)
    if w == 1 and h == 1:
        src = sliced_png(spec["sheet"], spec["col"], spec["row"])
        if not os.path.exists(src):
            print(f"MISSING {name}: {src}")
            return False
        convert(src, dst, name)
        return True
    sheet = Image.open(os.path.join(GFX, f"{spec['sheet']}.png")).convert("RGBA")
    x, y = spec["col"] * tile, spec["row"] * tile
    region = sheet.crop((x, y, x + w * tile, y + h * tile))
    convert_image(region, dst, name)
    return True


def run():
    manifest = json.load(open(os.path.join(TOOLS, "manifest.json")))
    tiles = manifest.get("tiles", {})
    os.makedirs(os.path.join(SRC, "tiles"), exist_ok=True)
    names = [name for name, spec in tiles.items() if _extract(name, spec)]
    _write_index(sorted(names))
    print(f"migrated {len(names)} tiles -> {SRC}")


def _write_index(names):
    lines = ["// AUTO-GENERATED by gfx/tools/migrate.py — one module per traced tile."]
    for n in names:
        lines.append(f'import {n} from "./tiles/{n}.js";')
    lines.append("")
    lines.append("export const TILES = {")
    for n in names:
        lines.append(f"  {n},")
    lines.append("};")
    with open(os.path.join(SRC, "index.js"), "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    run()
