"""Migrate the tiles named in manifest.json into semantic JS sprite modules.

Reads `manifest.json` (semantic_name -> {sheet, col, row}), mirrors each sliced
PNG into `assets/js/lib/space/sprites/tiles/<name>.js`, regenerates the
`sprites/index.js` registry, and writes a labeled verification montage so the
name->art mapping can be eyeballed.

Run `slice.py` first. Usage:
    python3 migrate.py
"""

import json
import os

from PIL import Image, ImageDraw

from png2js import convert

TOOLS = os.path.dirname(os.path.abspath(__file__))
GFX = os.path.dirname(TOOLS)
REPO = os.path.abspath(os.path.join(GFX, "..", "..", "..", ".."))
SLICED = os.path.join(GFX, "sliced")
SRC = os.path.join(REPO, "apps", "retro_hex_chat_web", "assets", "js", "lib", "space", "sprites")


def sliced_png(sheet, col, row):
    return os.path.join(SLICED, sheet, f"c{col:02d}_r{row:02d}.png")


def run():
    manifest = json.load(open(os.path.join(TOOLS, "manifest.json")))
    tiles = manifest.get("tiles", {})
    os.makedirs(os.path.join(SRC, "tiles"), exist_ok=True)
    names = []
    for name, spec in tiles.items():
        src = sliced_png(spec["sheet"], spec["col"], spec["row"])
        if not os.path.exists(src):
            print(f"MISSING {name}: {src}")
            continue
        convert(src, os.path.join(SRC, "tiles", f"{name}.js"), name)
        names.append(name)
    _write_index(sorted(names))
    _montage(tiles, names)
    print(f"migrated {len(names)} tiles -> {SRC}")


def _write_index(names):
    lines = ["// AUTO-GENERATED by gfx/tools/migrate.py — one module per traced tile."]
    for n in names:
        lines.append(f'import {n} from "./tiles/{n}.js";')
    lines.append("")
    lines.append("export const TILES = {")
    for n in names:
        lines.append(f"  {n},")
    lines.append("};")
    with open(os.path.join(SRC, "index.js"), "w") as f:
        f.write("\n".join(lines) + "\n")


def _montage(tiles, names, scale=8):
    cell = 16 * scale
    cols = 6
    rows = (len(names) + cols - 1) // cols
    mos = Image.new("RGBA", (cols * cell, rows * (cell + 16)), (28, 30, 40, 255))
    d = ImageDraw.Draw(mos)
    for i, name in enumerate(names):
        spec = tiles[name]
        src = sliced_png(spec["sheet"], spec["col"], spec["row"])
        x, y = (i % cols) * cell, (i // cols) * (cell + 16)
        t = Image.open(src).convert("RGBA").resize((cell, cell), Image.NEAREST)
        mos.alpha_composite(t, (x, y))
        d.text((x + 2, y + cell + 2), name, fill=(255, 255, 0, 255))
    mos.save(os.path.join(TOOLS, "_verify_tiles.png"))


if __name__ == "__main__":
    run()
