defmodule RetroHexChatWeb.ShowcaseSmokeTest do
  use RetroHexChatWeb.ConnCase, async: true

  @showcase_routes [
    "/showcase",
    "/showcase/button",
    "/showcase/input",
    "/showcase/label",
    "/showcase/textarea",
    "/showcase/select",
    "/showcase/checkbox",
    "/showcase/radio-group",
    "/showcase/switch",
    "/showcase/slider",
    "/showcase/toggle",
    "/showcase/toggle-group",
    "/showcase/alert",
    "/showcase/badge",
    "/showcase/progress",
    "/showcase/skeleton",
    "/showcase/tooltip",
    "/showcase/card",
    "/showcase/separator",
    "/showcase/tabs",
    "/showcase/accordion",
    "/showcase/avatar",
    "/showcase/table",
    "/showcase/icons",
    "/showcase/diagrams",
    "/showcase/window",
    "/showcase/menu",
    "/showcase/toolbar",
    "/showcase/status-bar",
    "/showcase/irc-tabs",
    "/showcase/chat-message",
    "/showcase/chat-input",
    "/showcase/tree-view",
    "/showcase/nicklist",
    "/showcase/game-cards",
    "/showcase/fieldset",
    "/showcase/dialog",
    "/showcase/dropdown-menu",
    "/showcase/breadcrumb",
    "/showcase/pagination",
    "/showcase/toast",
    "/showcase/context-menu",
    "/showcase/loading-spinner",
    "/showcase/empty-state",
    "/showcase/color-picker",
    "/showcase/scroll-area",
    "/showcase/conversations",
    "/showcase/hover-card",
    "/showcase/search-bar",
    "/showcase/topic-bar",
    "/showcase/formatting-toolbar",
    "/showcase/emoji-picker",
    "/showcase/autocomplete",
    "/showcase/tab-bar",
    "/showcase/reply-bar",
    "/showcase/connection-status",
    "/showcase/confirm-dialog",
    "/showcase/options-dialog",
    "/showcase/channel-dialog",
    "/showcase/address-book",
    "/showcase/about-dialog",
    "/showcase/channel-list",
    "/showcase/highlight-dialog",
    "/showcase/config-form",
    "/showcase/p2p-lobby",
    "/showcase/media-controls",
    "/showcase/file-transfer",
    "/showcase/bot-manager",
    "/showcase/admin-console",
    "/showcase/chat-layout"
  ]

  for route <- @showcase_routes do
    @tag :showcase
    test "GET #{route} returns 200", %{conn: conn} do
      conn = get(conn, unquote(route))
      assert conn.status == 200, "#{unquote(route)} returned #{conn.status}"
    end
  end
end
