import Config

# Configure your database
config :retro_hex_chat, RetroHexChat.Repo,
  username: System.get_env("PGUSER", "postgres"),
  password: System.get_env("PGPASSWORD", "postgres"),
  hostname: System.get_env("PGHOST", "localhost"),
  port: String.to_integer(System.get_env("PGPORT", "5432")),
  database: System.get_env("PGDATABASE", "retro_hex_chat_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :retro_hex_chat_web, RetroHexChatWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "dev_only_secret_key_base_not_for_production_run_mix_phx_gen_secret_to_replace",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:retro_hex_chat_web, ~w(--sourcemap=inline --watch)]},
    esbuild:
      {Esbuild, :install_and_run, [:retro_hex_chat_web_css, ~w(--sourcemap=inline --watch)]},
    esbuild:
      {Esbuild, :install_and_run,
       [:retro_hex_chat_web_retrohex_content_js, ~w(--sourcemap=inline --watch)]},
    esbuild:
      {Esbuild, :install_and_run, [:retro_hex_chat_web_v2_app_js, ~w(--sourcemap=inline --watch)]},
    npx:
      ~w(tailwindcss -c tailwind.config.js -i css/retrohex.css -o ../priv/static/assets/css/retrohex.css --watch) ++
        [cd: Path.expand("../apps/retro_hex_chat_web/assets", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :retro_hex_chat_web, RetroHexChatWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/retro_hex_chat_web/router\.ex$",
      ~r"lib/retro_hex_chat_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Basic auth for LiveDashboard
config :retro_hex_chat_web, :basic_auth, username: "admin", password: "retroforever"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# SaladUI component installation path
config :salad_ui,
  components_path:
    Path.join(File.cwd!(), "apps/retro_hex_chat_web/lib/retro_hex_chat_web/components/ui")

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Server roles — admin and operator nicknames
config :retro_hex_chat,
  admins: ["Admin"],
  server_operators: ["Oper"]
