defmodule RetroHexChatWeb.Endpoint do
  use Gettext, backend: RetroHexChatWeb.Gettext
  use Phoenix.Endpoint, otp_app: :retro_hex_chat_web

  # The session cookie is signed and encrypted to protect sensitive data
  # like chat nicknames and authentication tokens from being read or tampered with.
  @session_options [
    store: :cookie,
    key: "_retro_hex_chat_web_key",
    signing_salt: "OLXEOjJq",
    encryption_salt: "encrypted_cookie",
    same_site: gettext("Lax")
  ]

  socket "/socket", RetroHexChatWeb.UserSocket,
    websocket: [log: :debug],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], log: :debug],
    longpoll: [connect_info: [session: @session_options], log: :debug]

  # esbuild's dynamic-import chunks, ahead of the general handler because they
  # need a different cache policy. `Plug.Static` only grants `immutable` to a
  # request carrying `?vsn=`, which `~p` appends from the digest manifest — but
  # nothing here writes these URLs: esbuild bakes them into the bundle it emits,
  # so the browser asks for the bare path and gets an ETag instead. Production's
  # nginx log showed the result as nine 304s on every single page view.
  #
  # The filename already carries a content hash, which is the whole contract
  # `immutable` asks for: this URL's bytes can never change.
  plug Plug.Static,
    at: "/assets/js/chunks",
    from: {:retro_hex_chat_web, "priv/static/assets/js/chunks"},
    gzip: not code_reloading?,
    cache_control_for_etags: "public, max-age=31536000, immutable"

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :retro_hex_chat_web,
    gzip: not code_reloading?,
    only: RetroHexChatWeb.static_paths(),
    only_matching: RetroHexChatWeb.static_only_matching(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :retro_hex_chat_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  plug RetroHexChatWeb.PromExPlug, path: "/metrics"

  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: :debug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RetroHexChatWeb.Router
end
