defmodule RetroHexChat.VirtualSpace.Maps.Overworld do
  @moduledoc """
  Shared tile vocabulary for the outdoor maps, sourced from the human-made
  `overworld.png` sheet served at `/images/space/overworld.png`.

  Maps no longer ship traced pixel data: they reference tiles by semantic name,
  and each name resolves to a rectangle in a tileset sheet (`col`/`row` in tiles,
  `w`/`h` in tiles for multi-tile props). The client loads the sheet image once
  and slices it with `drawImage`, so the runtime art is the original pixel art.

  `tilesets/0` lists the sheets the client must load; `tiles/0` is the
  name → source-rect legend shared by every outdoor map.
  """

  @overworld_columns 40
  @character_columns 17
  @objects_columns 33
  @cave_columns 40
  @log_columns 12

  @tiles %{
    # Ground / texture (1×1)
    "grass" => %{ts: "overworld", col: 5, row: 9},
    "grass_tuft" => %{ts: "overworld", col: 6, row: 9},
    "grass_worn" => %{ts: "overworld", col: 6, row: 10},
    "grass_dark" => %{ts: "overworld", col: 4, row: 16},
    "dirt" => %{ts: "overworld", col: 1, row: 30},
    "flowers" => %{ts: "overworld", col: 0, row: 8},
    # Small props (1×1)
    "bush" => %{ts: "overworld", col: 1, row: 14},
    "rock" => %{ts: "overworld", col: 7, row: 5},
    "rock_s" => %{ts: "overworld", col: 9, row: 5},
    "log_l" => %{ts: "overworld", col: 3, row: 5},
    "log_m" => %{ts: "overworld", col: 4, row: 5},
    "log_r" => %{ts: "overworld", col: 5, row: 5},
    # Pond (3×3 of 1×1 tiles)
    "pond_tl" => %{ts: "overworld", col: 2, row: 6},
    "pond_tm" => %{ts: "overworld", col: 3, row: 6},
    "pond_tr" => %{ts: "overworld", col: 4, row: 6},
    "pond_ml" => %{ts: "overworld", col: 2, row: 7},
    "pond_c" => %{ts: "overworld", col: 3, row: 7},
    "pond_mr" => %{ts: "overworld", col: 4, row: 7},
    "pond_bl" => %{ts: "overworld", col: 2, row: 8},
    "pond_bm" => %{ts: "overworld", col: 3, row: 8},
    "pond_br" => %{ts: "overworld", col: 4, row: 8},
    # Brown cliff autotile: left/middle/right columns × lip/face/base rows.
    # `lip` is the grass edge on top of the drop (walkable); `face`/`base` are the
    # exposed rock wall (blocked). Left/right variants cap the ends of a run and
    # double as the west/east vertical side faces of a plateau.
    "cliff_lip_l" => %{ts: "overworld", col: 4, row: 11},
    "cliff_lip_m" => %{ts: "overworld", col: 5, row: 11},
    "cliff_lip_r" => %{ts: "overworld", col: 6, row: 11},
    "cliff_face_l" => %{ts: "overworld", col: 4, row: 12},
    "cliff_face_m" => %{ts: "overworld", col: 5, row: 12},
    "cliff_face_r" => %{ts: "overworld", col: 6, row: 12},
    "cliff_base_l" => %{ts: "overworld", col: 4, row: 14},
    "cliff_base_m" => %{ts: "overworld", col: 5, row: 14},
    "cliff_base_r" => %{ts: "overworld", col: 6, row: 14},
    # Multi-tile props
    "tree" => %{ts: "overworld", col: 5, row: 16, w: 2, h: 2},
    "house" => %{ts: "overworld", col: 6, row: 0, w: 5, h: 5},
    "boulder" => %{ts: "overworld", col: 9, row: 11, w: 3, h: 2},
    "cave" => %{ts: "overworld", col: 7, row: 11, w: 1, h: 2},
    # ---- Elfic Forest v4 vocabulary ------------------------------------
    # Generated by virtual.space/tools/export_map.py from the
    # render-verified rects (showcase.py CAT / RECT_FIX) — every rect below
    # was zoom-inspected against the sheets before shipping.
    # Ground / texture (1×1)
    "grass_plain" => %{ts: "overworld", col: 0, row: 0},
    "grass_scrub" => %{ts: "overworld", col: 0, row: 29},
    "gravel_light" => %{ts: "overworld", col: 14, row: 11},
    "crops_tl" => %{ts: "overworld", col: 0, row: 34},
    "crops_tr" => %{ts: "overworld", col: 1, row: 34},
    "crops_bl" => %{ts: "overworld", col: 0, row: 35},
    "crops_br" => %{ts: "overworld", col: 1, row: 35},
    # Water accents (drawn over pond tiles)
    "water_lily" => %{ts: "overworld", col: 2, row: 0},
    "water_lilies_cluster" => %{ts: "overworld", col: 4, row: 0, w: 2, h: 1},
    "water_ripple" => %{ts: "overworld", col: 16, row: 0},
    "stepping_stones" => %{ts: "cave", col: 7, row: 9, w: 3, h: 1},
    "stepping_stone" => %{ts: "cave", col: 10, row: 9},
    "rock_islet" => %{ts: "cave", col: 9, row: 7, w: 2, h: 2},
    "river_boulder" => %{ts: "overworld", col: 13, row: 8, w: 2, h: 2},
    "river_rock_cluster" => %{ts: "overworld", col: 11, row: 7, w: 2, h: 2},
    "river_rocks" => %{ts: "overworld", col: 11, row: 10, w: 3, h: 1},
    # Fences
    "fence_h" => %{ts: "overworld", col: 0, row: 19, w: 2, h: 1},
    "fence_wood" => %{ts: "overworld", col: 0, row: 17, w: 1, h: 2},
    # Village structures & furniture
    "house_large" => %{ts: "overworld", col: 6, row: 0, w: 5, h: 5},
    "roof_round_orange" => %{ts: "overworld", col: 3, row: 22, w: 3, h: 5},
    "door_arch_stone" => %{ts: "overworld", col: 25, row: 2, w: 1, h: 2},
    "gate_arch_wood" => %{ts: "overworld", col: 4, row: 31, w: 4, h: 3},
    "tower_stone_round" => %{ts: "overworld", col: 0, row: 21, w: 3, h: 7},
    "market_stall_awning" => %{ts: "overworld", col: 18, row: 22, w: 5, h: 6},
    "counter_wood" => %{ts: "overworld", col: 8, row: 6, w: 3, h: 3},
    "stool_wood" => %{ts: "overworld", col: 37, row: 8, w: 1, h: 2},
    "bench_wood" => %{ts: "overworld", col: 28, row: 4, w: 3, h: 2},
    "well_lidded" => %{ts: "overworld", col: 31, row: 5, w: 2, h: 2},
    "fountain_stone" => %{ts: "overworld", col: 22, row: 9, w: 3, h: 3},
    "anvil_forge" => %{ts: "overworld", col: 24, row: 17, w: 1, h: 3},
    "coal_rocks" => %{ts: "overworld", col: 12, row: 22, w: 2, h: 2},
    "coal_bed" => %{ts: "overworld", col: 11, row: 23},
    "flame_fire" => %{ts: "objects", col: 8, row: 3},
    # Goods & clutter
    "barrel_wood" => %{ts: "overworld", col: 33, row: 0, w: 1, h: 2},
    "crate_wood" => %{ts: "overworld", col: 30, row: 0, w: 1, h: 2},
    "crate_x" => %{ts: "overworld", col: 35, row: 8, w: 2, h: 2},
    "sack_flour" => %{ts: "overworld", col: 32, row: 0},
    "produce_crate_banana" => %{ts: "overworld", col: 26, row: 20, w: 1, h: 2},
    "produce_crate_greens" => %{ts: "overworld", col: 27, row: 20, w: 1, h: 2},
    "produce_crate_tomato" => %{ts: "overworld", col: 28, row: 20, w: 1, h: 2},
    "produce_crate_lemon" => %{ts: "overworld", col: 29, row: 20, w: 1, h: 2},
    "haystack" => %{ts: "overworld", col: 31, row: 3, w: 2, h: 2},
    "flowerpot_sprout" => %{ts: "overworld", col: 35, row: 0},
    "cauldron_grey" => %{ts: "objects", col: 4, row: 6, w: 2, h: 2},
    "pot_stone_a" => %{ts: "objects", col: 13, row: 0},
    "pot_stone_b" => %{ts: "objects", col: 14, row: 0},
    # Flora
    "tree_foliage" => %{ts: "overworld", col: 5, row: 16, w: 2, h: 2},
    "bush_round" => %{ts: "overworld", col: 0, row: 16, w: 2, h: 1},
    "hedge_block" => %{ts: "overworld", col: 0, row: 14, w: 1, h: 2},
    "bush_dead_grey" => %{ts: "overworld", col: 19, row: 17, w: 3, h: 3},
    "bush_clover" => %{ts: "objects", col: 2, row: 0},
    "flowers_white" => %{ts: "overworld", col: 0, row: 8},
    "tree_stumps" => %{ts: "overworld", col: 4, row: 1, w: 2, h: 2},
    "log_horizontal" => %{ts: "overworld", col: 3, row: 5, w: 3, h: 1},
    "stump_plain" => %{ts: "log", col: 0, row: 4, w: 2, h: 2},
    "stump_creature_sleep" => %{ts: "log", col: 8, row: 0, w: 2, h: 2},
    # Rocks
    "boulder_pile" => %{ts: "objects", col: 20, row: 0, w: 2, h: 2},
    "rock_boulder" => %{ts: "cave", col: 5, row: 4},
    "rock_pile" => %{ts: "cave", col: 5, row: 5},
    "rock_pebbles_scatter" => %{ts: "cave", col: 5, row: 6},
    "pebble_stone" => %{ts: "objects", col: 16, row: 1},
    "rock_small" => %{ts: "overworld", col: 6, row: 5},
    "rocks_row" => %{ts: "overworld", col: 7, row: 5, w: 4, h: 1},
    # Sacred & spooky
    "stone_slab_round" => %{ts: "overworld", col: 35, row: 5, w: 2, h: 2},
    "grave_stone_a" => %{ts: "objects", col: 0, row: 8},
    "grave_stone_b" => %{ts: "objects", col: 1, row: 8},
    "statue_relief" => %{ts: "overworld", col: 8, row: 31, w: 2, h: 3},
    "statue_pawn" => %{ts: "overworld", col: 10, row: 22, w: 1, h: 4},
    "statue_totem_a" => %{ts: "cave", col: 6, row: 0, w: 1, h: 3},
    "statue_totem_b" => %{ts: "cave", col: 7, row: 0, w: 1, h: 3},
    "idol_skull" => %{ts: "cave", col: 8, row: 0, w: 1, h: 3},
    "skull" => %{ts: "overworld", col: 28, row: 2},
    "bone" => %{ts: "overworld", col: 29, row: 2}
  }

  @doc "Tilesets the client must load for an outdoor map."
  @spec tilesets() :: [map()]
  def tilesets do
    [
      %{
        id: "overworld",
        src: "/images/space/overworld.png",
        tile: 16,
        columns: @overworld_columns
      },
      %{
        id: "character",
        src: "/images/space/character.png",
        tile: 16,
        columns: @character_columns
      },
      %{id: "objects", src: "/images/space/objects.png", tile: 16, columns: @objects_columns},
      %{id: "cave", src: "/images/space/cave.png", tile: 16, columns: @cave_columns},
      %{id: "log", src: "/images/space/log.png", tile: 16, columns: @log_columns}
    ]
  end

  @doc "Semantic tile name → source rectangle in a tileset sheet."
  @spec tiles() :: %{optional(String.t()) => map()}
  def tiles, do: @tiles

  @doc "Whether a tile name exists in the shared vocabulary."
  @spec known?(String.t()) :: boolean()
  def known?(name), do: Elixir.Map.has_key?(@tiles, name)
end
